# Tab bar
tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style custom
tab_bar_align left
tab_bar_min_tabs 1
tab_separator ""
tab_activity_symbol none
tab_title_template "{index}  {tab.active_wd.rsplit('/', 1)[-1]}"
