# -BEGIN_KITTY_FONTS-
#
font_family      family='Monaspace Neon Var' style=MonaspaceNeonVar-Regular variable_name=MonaspaceNeonVar wght=600 features='+calt +ss01 +ss02 +ss03 +ss07 +ss09 cv01=2'
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
# Or use `kitten --choose-fonts` to see what are the options
bold_font        family="Monaspace Xenon Var"   variable_name=MonaspaceXenonVar wght=600 features='+calt +ss01 +ss02 +ss03 +ss07 +ss09 cv01=2'
italic_font      family="Monaspace Radon Var"   variable_name=MonaspaceRadonVar wght=600 features='+calt +ss01 +ss02 +ss03 +ss07 +ss09 cv01=2'
bold_italic_font family='Monaspace Krypton Var' variable_name=MonaspaceKryptonVar wght=600 slnt=0 features='+calt +ss01 +ss02 +ss03 +ss07 +ss09 cv01=2'
# -END_KITTY_FONTS-

font_size 16.0
# text_composition_strategy platform

# os specifc
shell /run/current-system/sw/bin/bash --login

listen_on unix:/tmp/mykitty

# map ctrl+v send_key ctrl+v

# Tab Layout {{{

# include tab-bar-style-wezterm.conf
# include macos-tabs.conf
include tab-bar-style-macos.conf
# }}}
