# vim:fileencoding=utf-8:ft=kitty:foldmethod=marker

##############################################################################
#      Kitty Sessions section (To replace tmux), watch this video:           #
#                  https://youtu.be/lWKjvWvjk4Y                              #
##############################################################################

# Save current state to a session file (prompts for path, opens in $EDITOR)
# Also specify the filename when saving the session:
# ~/.config/kitty/sessions/dotfiles.kitty-session
map ctrl+shift+s save_as_session --use-foreground-process --relocatable

# Just leaving this here as an example, does not make sense because it would
# restart yabai each time, but useful to understand the alias and combine
# action_alias yabai_restart launch --type=background /bin/bash -c '"$HOME/.config/yabai/yabai_restart.sh"'
# map ctrl+b>h combine : goto_session $HOME/.config/kitty/sessions/winhome.kitty-session : yabai_restart

#: Path to a session file to use for all kitty instances. Can be
#: overridden by using the kitty --session =none command line option
#: for individual instances. See sessions
#: <https://sw.kovidgoyal.net/kitty/sessions/> in the kitty
#: documentation for details. Note that relative paths are interpreted
#: with respect to the kitty config directory. Environment variables
#: in the path are expanded. Changing this option by reloading the
#: config is not supported. Note that if kitty is invoked with command
#: line arguments specifying a command to run, this option is ignored.
startup_session $HOME/.config/kitty/sessions/home.kitty-session

# This is similar to tmux prefix + key
map ctrl+b>d goto_session $HOME/.config/kitty/sessions/dotfiles.kitty-session
map ctrl+b>o goto_session $HOME/.config/kitty/sessions/obsidian.kitty-session
map ctrl+b>1 goto_session $HOME/.config/kitty/sessions/networking.kitty-session
map ctrl+b>h goto_session $HOME/.config/kitty/sessions/home.kitty-session
map ctrl+b>b goto_session $HOME/.config/kitty/sessions/blogpost.kitty-session
map ctrl+b>p goto_session $HOME/.config/kitty/sessions/dots-private.kitty-session
map ctrl+b>a goto_session $HOME/.config/kitty/sessions/lua.kitty-session
map ctrl+b>k goto_session $HOME/.config/kitty/sessions/skitty.kitty-session
map ctrl+b>; goto_session $HOME/.config/kitty/sessions/scripts.kitty-session
# map ctrl+b>g goto_session $HOME/.config/kitty/sessions/glove80.kitty-session
map ctrl+b>g goto_session $HOME/.config/kitty/sessions/toucan.kitty-session
map ctrl+b>w goto_session $HOME/github/dotfiles-private/work/2026/work.kitty-session

action_alias launch_daily_note launch /bin/bash -c "$HOME/.config/scripts/macos/mac/misc/300-dailyNote.sh"
map ctrl+b>i launch_daily_note

# I call this alias after switching to the alternate session
action_alias update_kitty_name launch --type=background /bin/bash -c '"$HOME/.config/sketchybar/felixkratz-linkarzu/plugins/kitty_name.sh"'
# map ctrl+b>r update_kitty_name

# Switch to alternate kitty session or previous session
map ctrl+b>l goto_session -1
# map ctrl+b>l combine : goto_session -1 : update_kitty_name

action_alias launch_session_select launch --type=overlay /bin/bash -c "$HOME/.config/kitty/scripts/kitty-list-sessions.sh"
map ctrl+b>s launch_session_select

action_alias launch_zoxide_session launch --type=overlay /bin/bash -c "$HOME/.config/kitty/scripts/kitty-zoxide-session.sh"
map ctrl+b>z launch_zoxide_session

# Browse and select from the list of known projects defined via goto_session commands
map ctrl+b>n goto_session

