# BEGIN_KITTY_FONTS
# font_family      family='FiraCode Nerd Font' postscript_name=FiraCodeNF-Reg features="-cv01 -cv02 +cv06 -cv09 +cv12 +cv14 +cv16 -cv17 -cv18 -cv19 -cv21 -cv23 -cv24 -cv25 +cv26 -cv27 -cv28 +cv29 -cv30 +cv31 -cv32 -ss01 -ss02 +ss03 +ss04 +ss05 -ss06 -ss07 -ss08 +ss09 -ss10 -onum"
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
# END_KITTY_FONTS


font_family      family='Monaspace Neon Var' variable_name=MonaspaceNeonVar features='+calt +ss01 +ss02 +ss03 +ss06 +ss05 +ss09'
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0
text_composition_strategy legacy

# os specific
wayland_titlebar_color system
# linux_display_server wayland
wayland_titlebar_color background

allow_remote_control socket-only
listen_on unix:@mykitty

# The XDG Sound Theme kitty will use to play the bell sound. Defaults to the custom theme name specified in 
# the XDG Sound theme specification with the contents:
# 
# [Sound Theme]
# Inherits=name-of-the-sound-theme-you-want-to-use
# 
# Replace name-of-the-sound-theme-you-want-to-use with the actual theme name. Now all compliant applications 
# should use sounds from this theme.
linux_bell_theme __custom



# Tab Layout {{{

# include tab-bar-style-wezterm.conf
include tab-bar-style-gtk4.conf

# }}}

