# vim:fileencoding=utf-8:ft=kitty:foldmethod=marker

# Tab bar options
tab_bar_edge               top
tab_bar_margin_width       5.0
tab_bar_margin_height      7.5 7.5
tab_bar_style              custom
tab_bar_align              left
# For tabs, only the last directory of the active window's cwd
# I don't now how to do a condition to show the title that I set, but if no
# title just set the last dir in the path
tab_title_template " {session_name or tab.active_wd.rsplit('/', 1)[-1]}"
active_tab_title_template  " {index} {title.rstrip('/').rsplit('/', 1)[-1]}"
active_tab_font_style      normal
# Tab bar colors
tab_bar_background         #303030
tab_bar_margin_color       #303030
active_tab_foreground      #ffffff
inactive_tab_foreground    #ffffff
active_tab_background      #454545
inactive_tab_background    #303030
# Hide title bar
hide_window_decorations    yes
# Stop kitty shell-integration from changing window/tab titles based on the running command
# This is so that when I open Neovim I don't see that as the tab name
shell_integration no-title
#: The minimum number of tabs that must exist before the tab bar is
#: shown.
tab_bar_min_tabs 1
# kitty tab bar only shows tabs from the currently active session
# this works even if all the sessions run in the same os window
# https://github.com/kovidgoyal/kitty/issues/8911#issuecomment-3222346493
tab_bar_filter session:~ or session:^$
